// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:afb84c47-cf60-4d54-a1b6-a04b49f3cc80",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_S4QZnmPeo",
    "aws_user_pools_web_client_id": "4u49o5ucs49dba4g4t40gip7jd",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://q7skqqqldrhzxkq4sk54j7mh74.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
